import {
  GraduationCap,
  HeartHandshake,
  Award,
  Mic,
  Handshake,
  Clock,
  Sparkles,
  Sunrise,
  Users,
  Bot,
  Target,
  Palette,
  Brain,
  Code,
  BookOpen,
  PenLine,
  Calculator,
  Lightbulb,
  Puzzle,
  Smile,
  Footprints,
  Compass,
  ShieldCheck,
  Camera,
  Briefcase,
  type LucideIcon,
} from "lucide-react";

export const iconMap = {
  "graduation-cap": GraduationCap,
  "heart-handshake": HeartHandshake,
  award: Award,
  mic: Mic,
  handshake: Handshake,
  clock: Clock,
  sparkles: Sparkles,
  sunrise: Sunrise,
  users: Users,
  bot: Bot,
  target: Target,
  palette: Palette,
  brain: Brain,
  code: Code,
  "book-open": BookOpen,
  "pen-line": PenLine,
  calculator: Calculator,
  lightbulb: Lightbulb,
  puzzle: Puzzle,
  smile: Smile,
  footprints: Footprints,
  compass: Compass,
  "shield-check": ShieldCheck,
  camera: Camera,
  briefcase: Briefcase,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof iconMap;
